//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Donation
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Donation()
        {
            this.Donation_for_package = new HashSet<Donation_for_package>();
        }
    
        public int troma_kod { get; set; }
        public Nullable<int> user_kod { get; set; }
        public Nullable<System.DateTime> troma_date { get; set; }
        public Nullable<int> troma_amount { get; set; }
        public string receipt { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Donation_for_package> Donation_for_package { get; set; }
        public virtual User User { get; set; }
    }
}
