//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class products_for_packages
    {
        public int product_kod { get; set; }
        public Nullable<int> Free_lottery_minimum_amount { get; set; }
        public Nullable<int> price { get; set; }
    
        public virtual Product Product { get; set; }
    }
}
