//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.Selected_Products = new HashSet<Selected_Products>();
        }
    
        public int product_kod { get; set; }
        public string product_name { get; set; }
        public Nullable<int> torem_id { get; set; }
        public string prouduct_picture { get; set; }
        public Nullable<int> amount_of_tickets_even { get; set; }
        public string description { get; set; }
        public Nullable<int> winner_id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Selected_Products> Selected_Products { get; set; }
        public virtual User User { get; set; }
        public virtual products_for_packages products_for_packages { get; set; }
    }
}
