//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Selected_Products
    {
        public int product_kod { get; set; }
        public Nullable<int> amount_of_tickets { get; set; }
        public int donation_for_package_kod { get; set; }
    
        public virtual Donation_for_package Donation_for_package { get; set; }
        public virtual Product Product { get; set; }
    }
}
