//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tormim
    {
        public int torem_id { get; set; }
        public string Business_name { get; set; }
        public string torem_address { get; set; }
        public string torem_email { get; set; }
        public string torem_phone { get; set; }
    }
}
